log2count.table <- log2(count.table+epsilon)
print("Computing Raw parameters")
moyenneRaw <- colMeans(count.table)
medianeRaw <- colMedians(count.table)
maxRaw <- colMaxs(count.table)
minRaw <- colMins(count.table)
quantileRaw <- colQuantiles(count.table)
zeroRaw <- colCounts(count.table, value = 0)
dataRaw <- data.frame(moyenne= moyenneRaw, mediane = medianeRaw, quartile0 = quantileRaw[,1], quartile25 = quantileRaw[,2], quartile50 = quantileRaw[,3], quartile75 = quantileRaw[,4], quartile100 = quantileRaw[,5] ,max = maxRaw, min = minRaw, NombreZeros = zeroRaw, row.names = colnames(count.table))
print("Computing Log parameters")
moyenneLog <- colMeans(log2count.table)
medianeLog <- colMedians(log2count.table)
maxLog <- colMaxs(log2count.table)
minLog <- colMins(log2count.table)
quantileLog <- colQuantiles(log2count.table)
zeroLog <- colCounts(log2count.table, value = 5.030713)
dataLog <- data.frame(moyenne= moyenneLog, mediane = medianeLog, quartile0 = quantileLog[,1], quartile25 = quantileLog[,2], quartile50 = quantileLog[,3], quartile75 = quantileLog[,4], quartile100 = quantileLog[,5] ,max = maxRaw, min = minLog, NombreZeros = zeroLog,row.names = colnames(log2count.table))
