dataRld <- assay(rld)
rawData <- assay(dds)
print("Computing Raw parameters")
moyenneRaw <- colMeans(rawData)
medianeRaw <- colMedians(rawData)
maxRaw <- colMaxs(rawData)
minRaw <- colMins(rawData)
quantileRaw <- colQuantiles(rawData)
zeroRaw <- colCounts(rawData, value = 0)
dataRaw <- data.frame(moyenne= moyenneRaw, mediane = medianeRaw, quartile0 = quantileRaw[,1], quartile25 = quantileRaw[,2], quartile50 = quantileRaw[,3], quartile75 = quantileRaw[,4], quartile100 = quantileRaw[,5] ,max = maxRaw, min = minRaw, NombreZeros = zeroRaw, row.names = colnames(rawData))
print("Computing Log parameters")
moyenneLog <- colMeans(dataRld)
medianeLog <- colMedians(dataRld)
maxLog <- colMaxs(dataRld)
minLog <- colMins(dataRld)
quantileLog <- colQuantiles(dataRld)
zeroLog <- colCounts(dataRld, value = 5.030713)
dataLog <- data.frame(moyenne= moyenneLog, mediane = medianeLog, quartile0 = quantileLog[,1], quartile25 = quantileLog[,2], quartile50 = quantileLog[,3], quartile75 = quantileLog[,4], quartile100 = quantileLog[,5] ,max = maxRaw, min = minLog, row.names = colnames(dataRld))
